version: '3.8'

services:

  mongo:
    image: mongo:6
    container_name: proshop-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - C:\devops-ynov\tp:/data/db
    networks:
      - proshop-network #liaison 

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: proshop-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/proshop
      JWT_SECRET: abc123
      PAYPAL_CLIENT_ID: sb
    depends_on:
      - mongo
    networks:
      - proshop-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: proshop-frontend
    restart: always
    ports:
      - "3000:80"  #80 pour docke et 8000 pour la machine physique 
    depends_on:
      - backend
    networks:
      - proshop-network

networks:
  proshop-network:
    driver: bridge

    #mongo backeend frontend 