global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['proshop-prometheus:9090']

  - job_name: 'backend'
    static_configs:
      - targets: ['proshop-backend:5000']

  - job_name: 'frontend'
    static_configs:
      - targets: ['proshop-frontend:80']

  - job_name: 'node'
    static_configs:
      - targets: ['proshop-node-exporter:9100']

  - job_name: 'mongo'
    static_configs:
      - targets: ['proshop-mongodb-exporter:9216']